version: "2"

services:
  application:
    image: debian
    volumes:
      - ./:/var/www/app
  node:
<<<<<<< HEAD
    image: dung13890/vue-env
    environment:
      - NODE_ENV=development
=======
    image: "node:8"
    environment:
      - NODE_ENV=testing
>>>>>>> f7e81b4
    restart: always
    volumes_from:
      - application
    tty: true
    ports:
      - "8080:8080"
